///gggg asafsfsd
development:
  password: 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
  theme_id: "121082576947"
  timeout: 600s
  store: electro-6.myshopify.com
  ignore_files:
    - config/settings_data.json

home-1-1280:
  password: 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
  theme_id: "122318651443"
  timeout: 600s
  store: electro-6.myshopify.com
  ignore_files:
    - config/settings_data.json

home-2:
  password: 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
  theme_id: "122318716979"
  timeout: 600s
  store: electro-6.myshopify.com
  ignore_files:
    - config/settings_data.json

home-2-1280:
  password: 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
  theme_id: "122326024243"
  timeout: 600s
  store: electro-6.myshopify.com
  ignore_files:
    - config/settings_data.json

home-3:
  password: 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
  theme_id: "122326220851"
  timeout: 600s
  store: electro-6.myshopify.com
  ignore_files:
    - config/settings_data.json 

home-3-full-color:
  password: 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
  theme_id: "122326450227"
  timeout: 600s
  store: electro-6.myshopify.com
  ignore_files:
    - config/settings_data.json 

home-3-1280:
  password: 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
  theme_id: "122326482995"
  timeout: 600s
  store: electro-6.myshopify.com
  ignore_files:
    - config/settings_data.json

home-4:
  password: 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
  theme_id: "122327367731"
  timeout: 600s
  store: electro-6.myshopify.com
  ignore_files:
    - config/settings_data.json

home-4-1280:
  password: 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
  theme_id: "122328055859"
  timeout: 600s
  store: electro-6.myshopify.com
  ignore_files:
    - config/settings_data.json

home-5:
  password: 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
  theme_id: "122328842291"
  timeout: 600s
  store: electro-6.myshopify.com
  ignore_files:
    - config/settings_data.json

home-6:
  password: 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
  theme_id: "122347683891"
  timeout: 600s
  store: electro-6.myshopify.com
  ignore_files:
    - config/settings_data.json

home-7:
  password: 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
  theme_id: "122348273715"
  timeout: 600s
  store: electro-6.myshopify.com
  ignore_files:
    - config/settings_data.json

home-8:
  password: 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
  theme_id: "122349125683"
  timeout: 600s
  store: electro-6.myshopify.com
  ignore_files:
    - config/settings_data.json

home-9:
  password: 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
  theme_id: "122349453363"
  timeout: 600s
  store: electro-6.myshopify.com
  ignore_files:
    - config/settings_data.json

home-10:
  password: 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
  theme_id: "122349617203"
  timeout: 600s
  store: electro-6.myshopify.com
  ignore_files:
    - config/settings_data.json

home-11:
  password: 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
  theme_id: "122349879347"
  timeout: 600s
  store: electro-6.myshopify.com
  ignore_files:
    - config/settings_data.json

home-12:
  password: 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
  theme_id: "122357612595"
  timeout: 600s
  store: electro-6.myshopify.com
  ignore_files:
    - config/settings_data.json

home-13:
  password: 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
  theme_id: "122946748467"
  timeout: 600s
  store: electro-6.myshopify.com
  ignore_files:
    - config/settings_data.json
